package AOC2022;

import java.util.Arrays;

public class Day02 {
    public static void main(final String[] args) {
        System.out.printf("Solution for the first riddle: %s%n", one());
        System.out.printf("Solution for the second riddle: %s%n", two());
    }

    private static int one() {
        return Arrays.stream(input()).mapToInt(s -> switch (s) {
            case "A X" -> 3 + 1;
            case "B X" -> 0 + 1;
            case "C X" -> 6 + 1;
            case "A Y" -> 6 + 2;
            case "B Y" -> 3 + 2;
            case "C Y" -> 0 + 2;
            case "A Z" -> 0 + 3;
            case "B Z" -> 6 + 3;
            case "C Z" -> 3 + 3;
            default -> throw new IllegalArgumentException("Unexpected input: " + s);
        }).sum();
    }

    private static int two() {
        return Arrays.stream(input()).mapToInt(s -> switch (s) {
            case "A X" -> 3 + 0;
            case "A Y" -> 1 + 3;
            case "A Z" -> 2 + 6;
            case "B X" -> 1 + 0;
            case "B Y" -> 2 + 3;
            case "B Z" -> 3 + 6;
            case "C X" -> 2 + 0;
            case "C Y" -> 3 + 3;
            case "C Z" -> 1 + 6;
            default -> throw new IllegalArgumentException("Unexpected input: " + s);
        }).sum();
    }

    private static String[] testInput() {
        return """
                A Y
                B X
                C Z
                """.stripIndent().split("\n");
    }

    private static String[] input() {
        return """
                C Y
                A Z
                B X
                C Y
                B Y
                C X
                C Y
                B X
                B X
                A Z
                C X
                B Y
                B X
                B X
                A Z
                B X
                C Y
                C Y
                C X
                B X
                B X
                C Y
                C Y
                A Z
                C Y
                A X
                B Y
                C Y
                A Z
                B X
                B X
                C Y
                A Y
                A Y
                C Y
                C Z
                C Y
                C X
                C X
                B X
                C Y
                A Y
                C Z
                B X
                C Y
                B Y
                C Y
                A Y
                B X
                B Y
                A X
                A Y
                B X
                B X
                B X
                A Z
                C Y
                B Y
                A X
                A Y
                C X
                C X
                C Y
                B Y
                C X
                B X
                C X
                A Z
                B Y
                C X
                C Y
                B X
                B X
                C Y
                B X
                C Y
                A Z
                B Y
                B X
                B X
                B X
                C Y
                C Y
                A Y
                C X
                C X
                A Y
                C Y
                B X
                A Y
                C X
                C Y
                C X
                C X
                B Z
                C Y
                B X
                C Y
                A Y
                B Y
                B Y
                B X
                A Y
                C Y
                B X
                B Y
                A Y
                B X
                C Y
                C Y
                B Y
                B Y
                C Z
                C Y
                C X
                B X
                C Y
                B X
                C Y
                A Y
                A Y
                A Z
                C Z
                A Y
                B Y
                B X
                C X
                C Y
                C X
                B X
                B X
                A Y
                A Y
                C Y
                C Y
                A Z
                B X
                B X
                B X
                B Y
                B X
                B X
                C Y
                C Y
                C Y
                C X
                B X
                C Y
                B X
                A Z
                C Y
                C X
                A Z
                A Y
                A X
                C Y
                B X
                A Z
                C Y
                A Z
                C Y
                B Y
                A Z
                A Y
                A X
                A Z
                A Z
                C Y
                B X
                C Y
                C Y
                A Z
                B X
                C Y
                B X
                C Y
                A Y
                B X
                A Z
                A Z
                C Y
                A Z
                B Y
                B X
                A Z
                B X
                B X
                B X
                B Y
                C Y
                C Y
                C X
                A Y
                C X
                B X
                C Z
                B Y
                C Y
                A Y
                C X
                C X
                B X
                B X
                B X
                A Y
                B Y
                B X
                B X
                C Y
                A Y
                B X
                B X
                A Z
                C Y
                C Y
                B Y
                B X
                A Y
                B X
                B X
                A Z
                C Y
                A Y
                B X
                A Z
                C Z
                A Z
                B X
                B X
                B Y
                A Z
                C X
                B X
                C Y
                B X
                C Y
                C X
                A Z
                B X
                A Z
                C Y
                B X
                C X
                A Y
                B Y
                C Y
                B X
                B X
                B X
                B Y
                B X
                A X
                C Y
                B Y
                B Y
                C Y
                C Y
                C Y
                A Y
                A Y
                A X
                A Z
                C Y
                A Y
                C X
                C Y
                B Y
                C Y
                C Y
                B X
                C Y
                B X
                C Y
                C Y
                B X
                B Y
                B Y
                B X
                B Y
                B X
                C Y
                C Y
                C X
                C Y
                C X
                C X
                B Y
                A X
                C Y
                A Y
                C Z
                B X
                C Y
                A Y
                A Y
                C Y
                C Y
                B X
                B X
                B Y
                B Y
                C Y
                C X
                A Z
                C Y
                C Y
                C Y
                B Z
                A Z
                B X
                B Y
                C Y
                C Y
                B X
                A Z
                A Z
                B X
                C X
                C Y
                A X
                C Y
                B Y
                B X
                B X
                C Y
                B Y
                A Y
                B X
                B X
                C Z
                B Y
                B X
                C Y
                C Y
                C Y
                B X
                B Y
                C X
                B Y
                C Y
                C Y
                C X
                B X
                C Y
                B X
                C Y
                B X
                A Z
                C Y
                A X
                A Z
                B Z
                B Y
                C Y
                B X
                C Y
                C X
                B X
                B X
                B Y
                A Y
                C Y
                B X
                A Z
                C Y
                B X
                B X
                B X
                C Z
                B Y
                A Y
                B X
                C X
                A Y
                B X
                B X
                B X
                C Y
                C Y
                B X
                C Y
                C Y
                B X
                B Y
                B Y
                C Y
                B Y
                B X
                C X
                A Z
                B Y
                B X
                C Z
                A Y
                B X
                C X
                B X
                B X
                C Z
                B Y
                A X
                C X
                C X
                B X
                C Y
                A Z
                B X
                B X
                B X
                B X
                A Y
                C Y
                B Y
                B X
                A X
                B X
                C X
                C X
                B X
                C Y
                B Z
                A Z
                B X
                B X
                C Y
                B Z
                B X
                A Y
                B X
                A Z
                B X
                C X
                B X
                C X
                B X
                B X
                C Z
                B X
                A Y
                B X
                C Z
                B X
                C Y
                B X
                B Y
                B X
                B X
                C X
                B Y
                B Y
                A Y
                C Y
                B X
                B X
                C Y
                C Y
                C Y
                B X
                A Z
                C Y
                C Y
                A Z
                B X
                A Y
                C X
                B X
                C Y
                A Y
                B Y
                B Y
                A Z
                B X
                B X
                C Y
                B X
                B Y
                B X
                B X
                B X
                C Y
                C Y
                C Y
                C X
                B X
                B X
                C X
                C X
                B X
                A Y
                C Y
                C Y
                C Y
                C Z
                B X
                B X
                A Y
                B X
                A Y
                C X
                B X
                B X
                C Y
                C Y
                C Y
                A Y
                A Y
                A Y
                B X
                C Y
                B Y
                B X
                A Z
                C Y
                B X
                A Y
                B Y
                B Y
                B Y
                B Y
                C X
                A Y
                B X
                A Y
                B X
                C X
                C Y
                B X
                A Z
                C Y
                C Y
                B Y
                B X
                B X
                A Z
                B Y
                B Y
                C Y
                B X
                C X
                C Y
                B X
                B Y
                B X
                B X
                C Y
                B X
                B Y
                B X
                C Y
                B X
                A Y
                B X
                C Z
                B X
                C Y
                C Y
                B X
                B X
                C Y
                C Y
                C Y
                C X
                B Y
                B X
                C X
                B X
                C Z
                B X
                C Y
                A Y
                B X
                A Z
                C Y
                A Y
                B X
                A Z
                C Y
                C Y
                B X
                C Y
                A Y
                B X
                C X
                B Y
                C Y
                B X
                C X
                B X
                B Y
                A Y
                A Y
                A Y
                B X
                B X
                B X
                B X
                B Y
                B X
                B X
                B X
                A Z
                C X
                C Y
                A Z
                C X
                B X
                C Y
                B Y
                C Y
                B X
                C Y
                C Y
                C Y
                C Y
                C Y
                C Z
                B X
                B X
                C Y
                B X
                A Y
                C Y
                C X
                B Y
                C Y
                C Y
                A Y
                A Y
                C Y
                B Y
                C X
                B X
                C Y
                C Y
                B X
                B X
                B X
                A Z
                B Y
                B Y
                A Y
                C X
                B Y
                C Y
                C X
                B X
                B X
                C X
                B X
                C Y
                C Y
                B Y
                C Y
                B X
                B X
                A Z
                B Y
                A Z
                A X
                B Z
                A Y
                C Y
                C Y
                C Y
                B X
                A Z
                A Y
                B Y
                C Y
                B Y
                B X
                B X
                A Y
                C X
                C Y
                B X
                A Y
                A Z
                B X
                B X
                C Y
                B Y
                C Y
                C Y
                B Y
                B Y
                B X
                A Y
                B X
                B X
                B X
                B X
                C Y
                B X
                B Y
                C X
                C Y
                A Y
                B Y
                A Y
                C Y
                C Y
                A Z
                B X
                C Y
                A Z
                A Y
                B X
                B X
                B X
                C Y
                B X
                C Y
                B Y
                B X
                B Y
                A Y
                B X
                C Y
                C Y
                B X
                B X
                C Y
                C Y
                C Y
                B Z
                C Y
                B X
                C Y
                B Y
                C Y
                C X
                B X
                A Y
                A X
                A Z
                A Z
                B Y
                C X
                B X
                B Y
                B X
                B X
                A Z
                B X
                A Y
                C Z
                C Y
                C Y
                C Y
                A Y
                C X
                C Y
                A Z
                C Y
                B X
                A Y
                A Z
                B X
                A Y
                C X
                A Z
                A Y
                B X
                B X
                C Y
                C Y
                C Z
                A Z
                B X
                A Y
                B X
                B X
                B X
                C Y
                A Z
                C Y
                B X
                B Y
                C X
                C Y
                A Z
                A Z
                C Y
                B Y
                C Y
                C Y
                C X
                C Y
                C Y
                B X
                C Y
                B X
                B Y
                C Y
                C Y
                C X
                A Z
                B X
                B X
                C X
                C Y
                C X
                C X
                B X
                B Y
                B Y
                C Z
                A Y
                A Z
                B X
                B X
                C Y
                C Y
                A Y
                C Y
                B Y
                C Y
                B X
                C Y
                B Y
                B X
                C Y
                C Y
                B X
                C Z
                A Y
                B X
                C Y
                A Z
                C X
                C Y
                A Y
                B X
                A Y
                C Y
                B X
                C Y
                B X
                A Y
                C Y
                B Y
                B X
                B X
                C Y
                A Z
                A Z
                C X
                A Y
                B X
                C Y
                B X
                C X
                C Y
                C Y
                C Y
                C Y
                C X
                B Y
                B X
                B X
                C Y
                B Y
                B Y
                B X
                B X
                B X
                B Y
                B X
                B X
                B X
                C Y
                A Y
                A Y
                B X
                C Y
                C Y
                A Y
                C Y
                B Y
                C X
                B X
                B X
                A Y
                C Y
                B X
                B X
                B Y
                C Y
                B X
                C X
                B Y
                A Y
                A Y
                C Y
                C Y
                C Y
                C Y
                C Y
                B X
                C Y
                B Y
                B X
                B Y
                C Y
                B X
                B X
                B X
                B Y
                B X
                B X
                B X
                C Y
                B Y
                C Y
                B X
                B X
                B Y
                C X
                C X
                C Y
                B Y
                B X
                A Z
                B X
                B X
                C X
                C Y
                C Y
                B X
                A Z
                C Z
                C Y
                C Y
                C Y
                C X
                B Y
                B X
                C Y
                C Y
                C Y
                B Y
                B Y
                C Y
                C Y
                B Y
                A Z
                C Y
                A Z
                B X
                C Y
                A Y
                B X
                C Y
                C Y
                B X
                A X
                B X
                B X
                C Y
                C Z
                C Y
                A Y
                C Y
                C Y
                B X
                B X
                B X
                B X
                A Z
                C Y
                C Y
                B Y
                B X
                C Y
                C Y
                C Y
                B X
                A Y
                B X
                C Y
                B X
                B X
                C Y
                C Y
                B Y
                B Y
                C Y
                B Y
                C Y
                A Y
                A Y
                A Y
                C Y
                C Z
                B X
                A X
                C Y
                A Y
                C Y
                A Y
                B X
                B X
                B X
                B X
                B X
                C Z
                B X
                C Y
                C Y
                B Y
                A Z
                A Z
                C Y
                B Y
                C Z
                A Z
                C X
                A Y
                C Y
                C Y
                B X
                C Y
                B Y
                B Y
                C Y
                A X
                C Y
                B X
                A Y
                C X
                B Z
                C X
                B X
                B Y
                A Z
                A X
                B Z
                C Y
                B X
                B Y
                C X
                A Y
                C Y
                C Z
                B Y
                B Y
                B X
                B X
                C Y
                B X
                B Y
                C Y
                C X
                C Z
                C Z
                C Z
                A Y
                B X
                C Y
                C Y
                B X
                A Y
                B X
                A Y
                C X
                C X
                B Y
                A Y
                C Y
                A Y
                C Y
                C Y
                B X
                B X
                A X
                B X
                A Y
                C Y
                C Y
                C X
                A Y
                B X
                B Y
                B X
                B X
                B Z
                B X
                A Y
                C Y
                B X
                B X
                A Y
                A Z
                C Y
                C Y
                A Z
                A Z
                B X
                B X
                C Y
                B X
                B X
                A Y
                A Z
                B Y
                B X
                C Y
                C Y
                B X
                B X
                C X
                C Y
                B X
                B X
                B X
                B X
                B X
                C Y
                C Y
                A Y
                B Y
                B X
                A Z
                C Y
                B Y
                A Z
                C Y
                C Y
                B X
                A Z
                C Y
                A Y
                C X
                B X
                B X
                B Y
                B X
                A Z
                C Y
                B X
                B X
                B X
                B X
                B X
                B X
                C Y
                B X
                B Y
                B Y
                B Y
                C Z
                C Y
                B Y
                A Y
                A Y
                B Z
                B Y
                B Y
                B X
                B Y
                B Y
                C X
                A Z
                C Y
                C Y
                C Y
                B X
                B Y
                B X
                C Y
                C Y
                C Y
                B Y
                A Y
                C Y
                B X
                B X
                C Y
                B Y
                C Y
                B X
                B X
                B Y
                A Y
                C X
                C Z
                B X
                A Y
                C Y
                B X
                C Y
                B X
                C Z
                C Y
                C Y
                C Y
                A Z
                C X
                C Y
                C Y
                A Z
                A Z
                B X
                A Y
                C Y
                C Y
                B X
                A Z
                B X
                C Y
                B Y
                B X
                B X
                C Y
                C Y
                B Y
                C X
                B Y
                C Y
                B Y
                C Y
                B X
                C Y
                B X
                B Y
                B Y
                C X
                C Y
                A Z
                C Y
                C Y
                C Y
                A X
                A Y
                B Y
                C X
                B X
                C Y
                B X
                A Y
                B X
                C Y
                C Y
                C Y
                A Y
                B Y
                B Y
                B X
                A Z
                A Z
                B Z
                C Y
                B Y
                C Y
                B X
                A Z
                C Z
                B X
                C Y
                C Y
                C X
                C Y
                C Y
                C Z
                C Y
                B Y
                B X
                B Y
                B Y
                B X
                A Z
                C Y
                B X
                B X
                B Y
                B Y
                B X
                C X
                C Y
                C X
                B X
                B Y
                B Y
                A Y
                C Y
                B X
                A Y
                C Y
                B X
                B X
                C Y
                C Y
                C X
                B X
                C Z
                B X
                C Y
                A Y
                C X
                B X
                C Y
                B X
                C X
                A Y
                A Y
                A Y
                C Y
                B X
                B X
                B X
                B Y
                A X
                C X
                B X
                C Y
                B X
                B X
                A Y
                B X
                B X
                B X
                B X
                B Y
                B Y
                B X
                C X
                A Z
                C Y
                C Y
                C Y
                B Y
                C Y
                C Y
                B X
                B Y
                C Y
                A Z
                C Y
                B X
                B X
                C Y
                A Z
                C Y
                A Y
                B X
                C Y
                B X
                B Y
                C Y
                C X
                B X
                B Y
                B X
                B X
                B X
                B X
                C Y
                C Y
                A Y
                C Y
                B Z
                A Y
                C Y
                C Y
                B X
                A Y
                C Z
                C Y
                B Y
                C Y
                C Y
                B Y
                C Y
                B X
                B X
                C Y
                B X
                B X
                B Y
                B X
                B X
                B Y
                C X
                C Y
                B X
                A Y
                C X
                B X
                B X
                A X
                B Y
                C Y
                C Y
                B X
                A X
                A Y
                B Y
                B Y
                C Z
                B Y
                B Y
                B X
                B X
                C Y
                A Y
                C Y
                A Y
                B X
                C X
                B Y
                C Y
                B Y
                B Y
                C Y
                A Y
                C Y
                B X
                A X
                C Y
                B X
                B X
                B X
                C Y
                C Y
                C Y
                A Z
                A Z
                C Y
                A Y
                C Y
                B X
                B X
                C X
                B Y
                A Y
                A Z
                A Y
                C X
                B X
                C Y
                B Y
                B X
                A Y
                C Y
                B X
                A Y
                B Y
                C Y
                B Y
                B X
                C Y
                C Y
                B Y
                B X
                C Y
                B Y
                C X
                C Y
                B X
                B X
                C Y
                C Y
                A Y
                C X
                B X
                B X
                B Y
                A Y
                B Y
                B X
                C Y
                C Y
                C X
                B Y
                C Z
                C Y
                C Y
                B Y
                C Z
                B X
                C Y
                A Y
                A Z
                B Y
                B X
                C X
                A Y
                B X
                C Z
                B Y
                C Y
                B X
                B X
                B Y
                C Y
                B Y
                C Y
                C X
                B Y
                B X
                C Z
                B X
                B X
                B X
                B X
                A X
                B X
                C Y
                C X
                B X
                A Y
                C Y
                A Z
                C Y
                C Y
                C Y
                A Z
                B X
                C Y
                A Y
                B X
                B X
                C Y
                A Z
                B X
                C Y
                A Y
                A Z
                C Y
                A Y
                B Y
                B Y
                C Y
                C Y
                C Y
                B X
                C Y
                C Y
                B X
                B X
                A Z
                C X
                C Z
                A Z
                C Y
                B X
                B Y
                B X
                B Y
                C Y
                B X
                B X
                B X
                B X
                B X
                B Y
                C X
                C Y
                C Y
                B X
                B X
                B X
                C Y
                C Y
                C Y
                C Y
                A X
                B X
                B X
                A X
                B Y
                C Y
                C Y
                B Z
                C Y
                C Y
                B X
                B X
                C X
                A Y
                B Y
                B X
                C X
                B X
                B Y
                B X
                C Y
                C Y
                C Y
                B X
                A Z
                B X
                A X
                B X
                A Y
                C Y
                A Y
                C X
                B X
                B Y
                B X
                B X
                C Y
                A Y
                B Y
                A Y
                C Y
                B Y
                B Y
                B X
                A Z
                B X
                B X
                B X
                C Z
                B X
                C Y
                B X
                B X
                C Y
                C X
                B X
                C Y
                B X
                C Y
                C Z
                A Y
                B X
                C Y
                B Y
                C Y
                C Y
                C Y
                B Y
                B Y
                C Y
                A Y
                A Z
                C Y
                C Y
                C Y
                B X
                A Y
                C Z
                B Y
                C Y
                C Y
                B X
                B Y
                A X
                B X
                B Y
                B X
                C Y
                B X
                B Y
                B X
                A Z
                A Z
                B X
                B X
                B X
                C Y
                B X
                C Y
                A Y
                C X
                C Y
                A Z
                A Y
                B X
                B X
                C Y
                B X
                B Y
                A Y
                B X
                B X
                C X
                C X
                B X
                B Y
                C Y
                B X
                B X
                C Y
                B X
                B X
                C X
                B Y
                A Y
                C Y
                B X
                B X
                B Y
                C Y
                A Z
                B X
                C Y
                C Y
                B X
                B X
                A Y
                C Y
                C Y
                B X
                A Y
                B X
                B X
                A Z
                C Y
                B X
                B X
                C Y
                B Y
                C Y
                B X
                A Z
                C Y
                C Y
                B Z
                A Z
                B Z
                B X
                A Z
                C Y
                B Y
                C X
                A Z
                C Y
                A Y
                B X
                C Y
                C Y
                B X
                C Y
                B X
                C Y
                C Y
                B X
                B X
                C Y
                B Y
                A Y
                B X
                C Y
                A Y
                C Y
                C Y
                B X
                C Y
                B X
                B X
                B X
                C Y
                B X
                B Y
                B Y
                A Y
                A Y
                A Z
                B X
                C Y
                B Y
                B X
                B X
                C Y
                B Y
                C Y
                C Y
                A Z
                C Y
                C Y
                B Y
                A Y
                B Y
                C X
                B X
                B X
                B X
                B X
                A Z
                B X
                C X
                A Y
                C Y
                B X
                C Z
                C Y
                B X
                C Y
                B X
                B X
                A Y
                C Z
                B X
                B X
                C Y
                A Z
                A Y
                C X
                B Y
                B Y
                B X
                A Y
                C Y
                B X
                B Y
                B Y
                C Y
                C X
                A Z
                B Y
                C Y
                B X
                C X
                C X
                B Y
                A Z
                B Z
                B X
                B X
                A Z
                B Y
                C Y
                C Y
                B X
                C Z
                C Y
                C Y
                A Y
                C Y
                B Y
                B X
                C Y
                C Y
                A Y
                A Z
                A Z
                B X
                C Y
                B X
                B X
                B X
                B X
                A Z
                B X
                A X
                C Z
                C Y
                B Y
                A Y
                B X
                B Y
                A Z
                C Y
                C Y
                B X
                C Y
                C Y
                C X
                C Y
                B X
                B X
                B X
                C Y
                B Y
                B Y
                C Y
                C Y
                B X
                B X
                B X
                B X
                A Y
                C Y
                B X
                C X
                A Z
                C Y
                B X
                B Y
                B Y
                B Y
                C Z
                B Y
                A Y
                C X
                A Z
                C Y
                C Y
                C X
                A Y
                B Y
                A Y
                B X
                C X
                B X
                C Y
                B Y
                B X
                C Y
                C Y
                B X
                B Y
                B X
                A Z
                A Z
                A Y
                B X
                B X
                B Y
                C X
                A X
                B X
                B Y
                C X
                C Z
                C Y
                A Y
                C Y
                B X
                A Z
                B X
                B X
                A Z
                C X
                A Z
                C Y
                C Y
                A Z
                A Y
                B X
                C Z
                B X
                A Y
                B Y
                A X
                B Y
                B Y
                B Y
                B X
                C Y
                B X
                C Y
                C X
                C X
                A Z
                C Y
                B X
                A Y
                C Y
                A Y
                B X
                C Y
                C Y
                B X
                C Y
                B X
                C Y
                A Y
                A Z
                C Y
                B Z
                C Y
                C Y
                B X
                C Y
                C Y
                C Y
                B X
                A Y
                A Z
                B X
                A X
                B Z
                C Y
                B Z
                C Y
                B Y
                B Y
                C Y
                C Y
                B X
                C Y
                A Z
                B Y
                C Y
                C X
                A Y
                A Y
                B X
                B X
                B X
                A Y
                C Y
                A Y
                B Y
                C Y
                A Y
                A Y
                C Y
                B X
                C Y
                B X
                C Y
                B X
                B X
                C Y
                C X
                A Z
                C Y
                C Y
                A Z
                C Y
                A Y
                A X
                A Z
                B Y
                C Y
                B X
                C Y
                C Y
                C Y
                C Y
                A X
                B X
                C Y
                B Y
                B X
                B X
                A Y
                A Z
                C X
                C Y
                C Z
                C Y
                B Y
                C Y
                B X
                B X
                A X
                B X
                B X
                A Y
                C Y
                B X
                A Z
                C Y
                C Y
                A Z
                C Y
                C X
                B X
                B X
                B X
                C Y
                B Z
                C Y
                B X
                C X
                B X
                C Y
                C Y
                A Y
                C Y
                C Y
                C Z
                A Z
                C Y
                C Y
                C Y
                B X
                C X
                B Z
                C Y
                B X
                B X
                B X
                C Y
                B Y
                B X
                B Y
                A Y
                B Y
                B X
                C X
                C Y
                A Z
                B Y
                C Y
                B X
                C Y
                C X
                B X
                B X
                A Y
                B Y
                B X
                A Y
                B X
                C Y
                C Y
                C Y
                A Z
                A X
                C Y
                C Y
                C Y
                A Z
                B X
                B X
                A Y
                C Y
                C X
                C Y
                B X
                B X
                A Y
                A Y
                B X
                B X
                C Y
                B X
                B X
                A Y
                A Z
                B X
                A Y
                C Y
                C Y
                C Y
                B X
                B X
                C X
                A Y
                C Y
                B Y
                A Y
                C Z
                B X
                C Y
                B Y
                B X
                C Z
                A Y
                C X
                C Y
                C Y
                B X
                C X
                B X
                A Y
                C X
                B Y
                A Y
                A Y
                B X
                C Y
                B X
                C Y
                B Y
                C Y
                C Y
                B X
                B X
                B X
                B X
                B X
                C Y
                A Y
                C Y
                A Z
                A Y
                B X
                C X
                B X
                B Y
                C Z
                B Y
                B X
                C Y
                A X
                C X
                C Y
                B X
                C X
                A Y
                C Z
                C Y
                B X
                A Z
                A Y
                C Y
                C Y
                C Y
                C X
                B X
                A Z
                B Y
                C Y
                C Y
                B X
                B Y
                C X
                C Y
                B X
                B X
                B Z
                C Y
                B X
                B X
                B Z
                B X
                C Y
                C Y
                C Y
                C Z
                C Y
                B Y
                A Z
                A Z
                B X
                B Y
                A Z
                B Y
                B X
                B X
                B Y
                C X
                C Y
                A Y
                C X
                C X
                B Y
                A X
                B Y
                B X
                C Y
                C Y
                B X
                C Y
                A X
                C X
                C X
                B X
                B X
                C X
                B Y
                B Y
                A Y
                B X
                B X
                B X
                C X
                B X
                A Y
                C Y
                B X
                A Z
                B Y
                A Y
                B X
                B X
                C Y
                B Y
                A Z
                B X
                B X
                C Y
                A Y
                A Y
                A Z
                C Y
                A Y
                B X
                A Y
                B X
                C Y
                C Y
                C Y
                B X
                B Y
                B X
                C Y
                A Z
                A Z
                B Y
                B Y
                C X
                C X
                C Y
                B X
                C Y
                B X
                C Y
                C Y
                A Y
                A Y
                A Z
                A Y
                B X
                B X
                B X
                B Y
                C Y
                C X
                C Y
                B X
                B Y
                C Y
                C X
                C Y
                B X
                A Z
                C Y
                C Y
                B X
                A Z
                B X
                A Z
                A X
                A X
                B X
                B X
                C Y
                C X
                B Y
                C Z
                B X
                C Y
                A Z
                B X
                A Y
                C X
                B Y
                C Y
                B Y
                C X
                C Y
                C Y
                B X
                B Y
                C Y
                C X
                C Y
                B Y
                B Y
                B X
                B Z
                C Y
                C Y
                B X
                C Y
                C Y
                C Y
                B Y
                B Y
                C Y
                C Y
                C X
                B Z
                C Y
                C Y
                C Y
                B Y
                C X
                B Y
                A Y
                B X
                B Y
                A Z
                C Y
                B X
                A X
                C X
                B X
                B X
                A Y
                A Y
                A Y
                A Y
                B X
                B X
                A Z
                A Z
                C Y
                B X
                A Z
                B X
                B X
                C Y
                A Y
                B X
                B X
                A Y
                B X
                A X
                C Y
                B X
                B X
                A Z
                C Y
                B Y
                C Y
                A Z
                B X
                C X
                B Y
                C X
                B X
                B X
                C X
                A Y
                B X
                B Y
                B X
                C Y
                B X
                A Y
                B X
                C Y
                B Z
                B X
                A Z
                B X
                A Z
                A Y
                B Z
                B Y
                B X
                B X
                B Z
                B X
                C Y
                B Y
                A Z
                C Y
                B X
                B Y
                A Y
                C Y
                C Y
                B X
                B X
                C Y
                B X
                C Y
                B X
                B X
                A Y
                C Y
                A Y
                A Y
                A Y
                C Y
                C Y
                A Z
                B X
                A Y
                C Y
                B X
                C X
                B Y
                C Z
                C Y
                B X
                C Y
                C Y
                B X
                B X
                B X
                C X
                C X
                B X
                C X
                C X
                C X
                A Z
                B Y
                B X
                B X
                B X
                C Y
                A Z
                B Y
                B X
                B X
                B Y
                A Z
                B X
                C Y
                C Y
                A Z
                C Y
                B X
                A Y
                C Y
                B X
                """.stripIndent().split("\n");
    }
}
